# Generated by Django 4.2.7 on 2023-11-24 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('batch', models.CharField(blank=True, max_length=255)),
                ('Trainer', models.ForeignKey(limit_choices_to={'groups__name': 'Trainer', 'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.CharField(max_length=200)),
                ('branch_code', models.CharField(max_length=50, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ('state', 'district'),
            },
        ),
        migrations.CreateModel(
            name='ComputerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('Name', models.CharField(max_length=50)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Computer Brands',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('Name', models.CharField(max_length=50)),
                ('Floor', models.CharField(choices=[('G', 'Ground'), ('I', 'First'), ('II', 'Second')], max_length=300)),
                ('Type', models.CharField(choices=[('class', 'Class Room'), ('conference', 'Confrence Hall')], max_length=300)),
                ('NoofSeats', models.IntegerField()),
                ('Branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.branch')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('Category', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop')], max_length=300)),
                ('Code', models.CharField(editable=False, max_length=50, unique=True)),
                ('RentalorOwn', models.CharField(choices=[('rental', 'Rental'), ('own', 'Own')], max_length=300)),
                ('SerialNo', models.CharField(blank=True, max_length=50, null=True)),
                ('DateofPurchase', models.DateField()),
                ('DateofReturn', models.DateField()),
                ('ActualDateofReturn', models.DateField()),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.computerbrand')),
                ('ResponsibleTrainer', models.ForeignKey(limit_choices_to={'groups__name': 'Trainer', 'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ResponsibleTrainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.branch')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=255)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('Reservation_Type', models.CharField(choices=[('class', 'Class'), ('meeting', 'Meeting')], max_length=300)),
                ('From', models.DateField()),
                ('starttime', models.TimeField()),
                ('To', models.DateField()),
                ('endtime', models.TimeField()),
                ('Purpose', models.CharField(max_length=50)),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.batch')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.room')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Room Allocation',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('Dist_Name', models.CharField(max_length=255)),
                ('State', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.state')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('course', models.CharField(max_length=50)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='State', limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.district'),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.state'),
        ),
        migrations.AddField(
            model_name='batch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.branch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
