# Generated by Django 4.2.6 on 2023-11-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceAllocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Type',
            field=models.CharField(choices=[('class', 'Class Room'), ('conference', 'Conference Hall')], max_length=300),
        ),
    ]
