# Generated by Django 4.2.6 on 2023-11-27 05:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceAllocator', '0002_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomallocation',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.branch'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='Batch',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Branch', chained_model_field='branch', limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.batch'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='Room',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Branch', chained_model_field='Branch', limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.room'),
        ),
    ]
