# Generated by Django 4.2.7 on 2023-11-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceAllocator', '0003_roomallocation_branch_alter_roomallocation_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_closed',
        ),
    ]
