# Generated by Django 4.2.7 on 2023-11-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceAllocator', '0004_remove_batch_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='ResponsibleTrainer',
        ),
    ]
