# Generated by Django 4.2.7 on 2023-11-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemallocation',
            name='students',
            field=models.ForeignKey(limit_choices_to={'Have_Own_System': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
    ]
