# Generated by Django 4.2.6 on 2023-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_systemallocation_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemallocation',
            name='From',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='systemallocation',
            name='To',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
