# Generated by Django 4.2.7 on 2023-11-26 05:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceAllocator', '0002_alter_room_type'),
        ('Student', '0003_systemallocation_from_systemallocation_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemallocation',
            name='students',
        ),
        migrations.AddField(
            model_name='systemallocation',
            name='Batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.batch'),
        ),
        migrations.AddField(
            model_name='systemallocation',
            name='stud',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Batch', chained_model_field='Batch', limit_choices_to={'Have_Own_System': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
    ]
