# Generated by Django 4.2.6 on 2023-11-27 05:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceAllocator', '0002_alter_room_type'),
        ('Student', '0006_systemallocation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemallocation',
            name='students',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Batch', chained_model_field='Batch', limit_choices_to={'Have_Own_System': False, 'systemallocation__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student'),
        ),
        migrations.AlterField(
            model_name='systemallocation',
            name='system',
            field=models.ForeignKey(limit_choices_to={'systemallocation__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.system'),
        ),
    ]
