# Generated by Django 4.2.7 on 2023-11-28 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0009_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemallocation',
            options={'ordering': ['isactive']},
        ),
        migrations.AddField(
            model_name='systemallocation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemallocation',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemallocation',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
