# Generated by Django 4.2.6 on 2023-11-28 16:19

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceAllocator', '0005_remove_system_responsibletrainer'),
        ('Student', '0010_alter_systemallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemallocation',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.branch'),
        ),
        migrations.AlterField(
            model_name='systemallocation',
            name='Batch',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Branch', chained_model_field='branch', limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ResourceAllocator.batch'),
        ),
    ]
